spring.application.name=hotel-booking-system

server.port=${PORT:-8080}

spring.datasource.url=jdbc:mysql://hopper.proxy.rlwy.net:21644/railway
spring.datasource.username=root
spring.datasource.password=RQVshXTRFNUqJmaaGenBVDnGZftovgzN
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=sdmadkjasndkjasndksandkjsandkjsandksankdnsakdjnnskd
jwt.expiration-ms=86400000
